// resources/js/console/Billing/Plans/Plans.tsx
import { useValues } from 'kea';
import React, { useState } from 'react';
import { BoxArrowUpRight } from 'react-bootstrap-icons';
import userBlogsLogic from '../../logic/userBlogsLogic';
import getSubdomain from "../../logic-helpers/subdomain";
import Frequency from "./Frequency";
import Plan from "./Plan";
import {SubscriptionFrequency, SubscriptionPlan} from "../../types";

interface PlansProps {

    onSubscriptionCreate: (plan: SubscriptionPlan, frequency: SubscriptionFrequency) => any
    onSubscriptionUpdate: (plan: SubscriptionPlan, frequency: SubscriptionFrequency) => any,
    onSubscriptionCancel: () => any,

}

export default function Plans({onSubscriptionCreate, onSubscriptionCancel, onSubscriptionUpdate} : PlansProps) {

    const subdomain = getSubdomain();

    const { findBlogBySubdomain } = useValues(userBlogsLogic);
    const { blog: { subscription: currentSubscription} } = findBlogBySubdomain(subdomain);

    const [frequency, setFrequency] = useState
        (currentSubscription ? currentSubscription.frequency : 'monthly'); // monthly|yearly

    return <div>
        <div className="section-title plans-title">
            <div className="title">Plans</div>
            <div className="frequency-selector">
                <Frequency frequency={frequency} setFrequency={setFrequency} type="monthly" name="Monthly" />
                <Frequency frequency={frequency} setFrequency={setFrequency} type="yearly" name="Yearly" />
            </div>
        </div>
        <div className="section-content">
            <div className="plans">
                {
                    (['A', 'B', 'C', 'D', 'E'] as SubscriptionPlan[]).map(plan =>
                        <Plan
                            key={plan}
                            type={plan}
                            frequency={frequency}
                            onCreate={onSubscriptionCreate}
                            onUpdate={onSubscriptionUpdate}
                            onCancel={onSubscriptionCancel}
                        />
                    )
                }
            </div>
            <div className="section-desc">
                Prices are shown in USD, including all VAT charges <br/>
                <div>
                    <a href="/pricing" className="link" target="_blank">
                        <span>Pricing</span>
                        <span className="icon"><BoxArrowUpRight /></span>
                    </a>
                </div>
            </div>
        </div>

    </div>;

}

// frontend/src/routes/console/[subdomain]/billing/Plans/Plans.svelte
<script lang="ts">
	import { Link, Switch, Tag } from "@hyvor/design/components";
    import type { SubscriptionFrequency, SubscriptionPlan } from "../../../lib/types";
	import PlanNotices from "./PlanNotices.svelte";
	import { IconBoxArrowUpRight } from "@hyvor/icons";
	import Plan from "./Plan.svelte";

    let frequency: SubscriptionFrequency = 'monthly';

    const planNames = [
        'starter',
        'growth',
        'premium',
        'team',
        'business',
        'enterprise'
    ] as SubscriptionPlan[];

</script>

<div class="title">

    <div class="left">Plans</div>

    <div class="right">

        <span class="yearly">
            Pay Yearly
            <span class="yearly-tag">
                <Tag color="blue" size="x-small">
                    17% off
                </Tag>
            </span>
        </span>

        <Switch 
            checked={frequency === 'yearly'}
            on:change={() => {
                frequency = frequency === 'monthly' ? 'yearly' : 'monthly';
            }}
        />

    </div>

</div>

<div class="content">
    <PlanNotices />

    <div class="plans">
        {#each planNames as plan}
            <Plan name={plan} {frequency} />
        {/each}
    </div>

    <div class="section-desc">
        Prices are shown in USD, including all VAT charges <br/>
        <div>
            <Link href="/pricing" target="_blank">
                <span>Pricing</span>
                <IconBoxArrowUpRight slot="end" />
            </Link>
        </div>
    </div>

</div>


<style>

    .title {
        margin-bottom: 15px;
        display: flex;
        align-items: center;
    }
    .title .left {
        font-size: 20px;
        font-weight: 600;
        flex: 1;
    }

    .yearly {
        font-size: 14px;
        font-weight: 500;
        color: var(--text-light);
        position: relative;
        margin-right: 25px;
    }

    .yearly-tag {
        position: absolute;
        bottom: 100%;
        margin-bottom: -1px;
        right: -20px;
    }

    .section-desc {
        font-size: 14px;
        text-align: center;
        padding: 10px;
        color: var(--text-light);
    }

</style>
