// resources/js/console/Integrations/HyvorTalk/HyvorTalk.tsx
import React, {useState} from "react";
import DualSetting from "../../ReusableComponents/DualSetting";
import NavLink from "../../ReusableComponents/NavLink";
import getSubdomain from "../../logic-helpers/subdomain";
import UserPermissions from "../../services/UserPermissions";
import Callout, {CalloutColors} from "../../ReusableComponents/Callout";
import hyvorTalkLogic from "./hyvorTalkLogic";
import {useActions, useValues} from "kea";
import Loader from "../../ReusableComponents/Loader";
import {PopupConfirm} from "../../ReusableComponents/Popup";
import blogLogic from "../../logic/blogLogic";
import {toast} from "react-toastify";
import UpgradeRequired from "../../ReusableComponents/UpgradeRequired";

export default function HyvorTalk() {

    const subdomain = getSubdomain();
    const isOwner = UserPermissions.isOwner();

    const logic = hyvorTalkLogic({subdomain});
    const { loadAjax, deleteIntegrationAjax, data } = useValues(logic);
    const { createIntegration, deleteIntegration } = useActions(logic);

    const { updateBlogSave } = useActions(blogLogic({subdomain}));

    const [isConnecting, setIsConnecting] = useState(false);
    const [isConnectConfirming, setIsConnectConfirming] = useState(false);
    const [isDisconnecting, setIsDisconnecting] = useState(false);

    const embedCode = data.connected ?
`<script async src="https://talk.hyvor.com/embed/embed.js" type="module"></script>
<hyvor-talk-comments 
    website-id="${data.data.website_id}" 
    page-id="{{ _post.id }}"
    page-url="{{ _post.url }}"
></hyvor-talk-comments>` : '';

    function handleAddingCode() {

        const promise = new Promise((resolve, reject) => {
            try {
                updateBlogSave({
                    data: {'comments_code': embedCode},
                    onUpdate: resolve
                })
            } catch (e) {
                reject();
            }
        })

        toast.promise(promise, {
            pending: 'Updating code...',
            success: 'Code updated successfully!',
            error: 'Failed to update code.'
        })

    }

    if (!isOwner) {
        return <Callout
            color={CalloutColors.RED}
            text="Only the owner of the blog can manage the Hyvor Talk integration."
        />;
    }

    return <UpgradeRequired
        minPlan="growth"
        trialAllowed={false}
        text={
            <div>
                This integration allows you to use <a href="https://talk.hyvor.com" target="_blank" style={{textDecoration: 'underline'}}>Hyvor Talk</a> on your blog for FREE. However, it is only available for blogs on the <b>Growth plan</b> or higher. Please upgrade your plan to use this integration.
            </div>
        }
        allow={data.connected}
    >
        <div className="integration hyvor-talk">

            {
                loadAjax.status === 'success' ?

                <div>

                    <DualSetting
                        title="Introduction"
                        right={
                            <div>
                                <a href="https://talk.hyvor.com" target="_blank" className="link">Hyvor Talk</a> is our own commenting platform. You can use it on your blog for free.
                                <ul>
                                    <li>
                                        Connect your blog to a website in Hyvor Talk
                                    </li>
                                    <li>
                                        Use the same HYVOR account (for the owner)
                                    </li>
                                    <li>
                                        Completely free
                                    </li>
                                    <li>
                                        Fast, secure, and privacy-focused
                                    </li>
                                </ul>
                            </div>
                        }
                    />

                    <DualSetting
                        title="Connect Hyvor Talk"
                        right={
                            <div>
                                {
                                    data.connected ?
                                    <>
                                        <div className="connection-status">
                                            This blog is connected to website ID <strong>{data.data.website_id}</strong> in Hyvor Talk. You can manage comments from the Hyvor Talk Console.
                                        </div>
                                        <a
                                            className="button small"
                                            href={`https://talk.hyvor.com/consolev3/${data.data.website_id}/comments`}
                                            target="_blank"
                                        >Go to Hyvor Talk Console</a>
                                        <button
                                            className="button small danger disconnect-button"
                                            onClick={() => setIsDisconnecting(true)}
                                        >Disconnect</button>
                                    </> :
                                    <>
                                        <div className="connection-status">
                                            This blog is not connected to a website in Hyvor Talk.
                                        </div>
                                        <button
                                            className="button"
                                            onClick={() => setIsConnecting(true)}
                                        >Connect Now</button>
                                    </>
                                }
                            </div>
                        }
                    />

                    {
                        data.connected &&
                        <DualSetting
                            title="Embed Code"
                            right={
                                <div>
                                    <div className="connection-status">
                                        Update <NavLink href={`/console/${subdomain}/settings/comments`} className="global-jump-link"><strong>Settings &rarr; Comments & Newsletter &rarr; Comments Embed Code</strong></NavLink> by clicking the button below. You may customize the code if you want.
                                    </div>
                                    <pre><code>{embedCode}</code></pre>
                                    <button className="button small" onClick={handleAddingCode}>Update "Comments Embed Code"</button>
                                </div>
                            }
                        />
                    }

                </div> :
                <Loader padding={100} />
            }

            {
                isConnecting &&

                <PopupConfirm
                    title="Connect Hyvor Talk"
                    text={
                        <div>
                            <p>
                                Please confirm that you want to create a website ID in Hyvor Talk for this blog.
                            </p>
                            <ul>
                                <li>A new Hyvor Talk website ID will be created under your HYVOR account.</li>
                                <li>It is free of charge.</li>
                                <li>It can only be used on this blog.</li>
                                <li>If you have any other websites on Hyvor Talk, you will need a separate subscription.</li>
                            </ul>
                        </div>
                    }
                    name="Connect Now"
                    onClick={() => {
                        setIsConnectConfirming(true);
                        createIntegration({
                            onSuccess: () => {
                                setIsConnectConfirming(false);
                                setIsConnecting(false);
                            }
                        });
                    }}
                    onCancel={() => setIsConnecting(false)}
                    isLoading={isConnectConfirming}
                />
            }

            {
                isDisconnecting &&
                <PopupConfirm
                    title="Disconnect Hyvor Talk"
                    text={
                        <div>
                            <Callout
                                color={CalloutColors.RED}
                                title="Caution"
                                text="You cannot connect this blog to the same website ID again."
                            />
                            Are you sure you want to disconnect this blog from Hyvor Talk? This will not delete your Hyvor Talk Website ID. You will have to delete it manually from the Hyvor Talk Console.
                        </div>
                    }
                    name="Disconnect"
                    onClick={() => {
                        deleteIntegration({
                            onSuccess: () => {
                                setIsDisconnecting(false);
                            }
                        });
                    }}
                    onCancel={() => setIsDisconnecting(false)}
                    isLoading={deleteIntegrationAjax.status === 'loading'}
                    buttonClass="danger"
                />
            }

        </div>

    </UpgradeRequired>
}

// frontend/src/routes/console/[subdomain]/integrations/hyvor-talk/+page.svelte
<script lang="ts">
	import {
		Button,
		ButtonGroup,
		Callout,
		Link,
		Loader,
		Modal,
		SplitControl,
		toast
	} from '@hyvor/design/components';
	import UpgradeRequired from '../../billing/UpgradeRequired.svelte';
	import {
		loadHyvorTalk,
		type HyvorTalkIntegrationData,
		createHyvorTalkIntegration,
		deleteHyvorTalkIntegration
	} from './hyvorTalkActions';
	import { onMount } from 'svelte';
	import Newsletter from './Newsletter/Newsletter.svelte';
	import Comments from './Comments/Comments.svelte';
	import Memberships from './Memberships/Memberships.svelte';

	let isLoading = true;
	let data: HyvorTalkIntegrationData;

	let isConnecting = false;
	let isDisconnecting = false;

	function handleConnect() {
		isConnecting = false;
		const toastId = toast.loading('Connecting to Hyvor Talk...');

		createHyvorTalkIntegration()
			.then((res) => {
				data = {
					connected: true,
					data: res
				};
				toast.success('Hyvor Talk connected successfully', { id: toastId });
			})
			.catch((_) => toast.error('Failed to connect to Hyvor Talk', { id: toastId }));
	}

	function handleDisconnect() {
		isDisconnecting = false;
		const toastId = toast.loading('Disconnecting from Hyvor Talk...');

		deleteHyvorTalkIntegration()
			.then((_) => {
				data = {
					connected: false
				};
				toast.success('Hyvor Talk disconnected successfully', { id: toastId });
			})
			.catch((_) => toast.error('Failed to disconnect from Hyvor Talk', { id: toastId }));
	}

	onMount(() => {
		loadHyvorTalk()
			.then((res) => (data = res))
			.catch((_) => toast.error('Failed to load Hyvor Talk integration data'))
			.finally(() => (isLoading = false));
	});
</script>

<UpgradeRequired minPlan="growth" trialAllowed={false}>
	<div slot="upgrade-text">
		This integration allows you to use <a
			href="https://talk.hyvor.com"
			target="_blank"
			style="text-decoration:underline">Hyvor Talk</a
		> on your blog for FREE. Upgrade to the Growth plan or higher to use this integration. This integration
		is not available in the trial period.
	</div>

	{#if isLoading}
		<Loader full />
	{:else}
		<SplitControl label="Introduction">
			<div>
				<Link href="https://talk.hyvor.com" target="_blank">Hyvor Talk</Link> is a privacy-first commenting,
				newsletter, and memberships platform. You can use it for free on your blog.

				<p>
					When you connect Hyvor Talk to your blog, we will automatically create a new website ID in
					Hyvor Talk for this blog under your account. You can manage the comments from the Hyvor
					Talk Console.
				</p>
			</div>
		</SplitControl>

		<SplitControl label="Connect Hyvor Talk">
			{#if data.connected}
				<div class="connection-status">
					This blog is connected to website ID <strong>{data.data.website_id}</strong> in Hyvor Talk.
					You can manage comments from the Hyvor Talk Console.
				</div>

				<Button
					as="a"
					href={`https://talk.hyvor.com/console/${data.data.website_id}/comments`}
					target="_blank"
					size="small"
					style="margin-right:6px;"
				>
					Go to Hyvor Talk Console
				</Button>

				<Button color="red" size="small" on:click={() => (isDisconnecting = true)}
					>Disconnect</Button
				>
			{:else}
				<div class="connection-status">This blog is not connected to a website in Hyvor Talk.</div>

				<Button on:click={() => (isConnecting = true)}>Connect Now</Button>
			{/if}
		</SplitControl>

		{#if data.connected}
			<div class="embed-code">
				<SplitControl label="Embed Codes">
					<div slot="nested">
						<Comments websiteId={data.data.website_id} />
						<Newsletter websiteId={data.data.website_id} />
						<Memberships websiteId={data.data.website_id} />
					</div>
				</SplitControl>
			</div>
		{/if}
	{/if}
</UpgradeRequired>

{#if isConnecting}
	<Modal title="Connect Hyvor Talk" bind:show={isConnecting}>
		<div>
			<p>Please confirm that you want to create a website ID in Hyvor Talk for this blog.</p>
			<ul>
				<li>A new Hyvor Talk website ID will be created under your HYVOR account.</li>
				<li>This new website can <b>only</b> be used on this blog.</li>
				<li>It is free of charge.</li>
				<li>
					If you have any other websites on Hyvor Talk, you will need a separate subscription.
				</li>
			</ul>
		</div>

		<svelte:fragment slot="footer">
			<ButtonGroup>
				<Button variant="invisible" on:click={() => (isConnecting = false)}>Cancel</Button>
				<Button on:click={handleConnect}>Confirm</Button>
			</ButtonGroup>
		</svelte:fragment>
	</Modal>
{/if}

{#if isDisconnecting}
	<Modal title="Disconnect Hyvor Talk" bind:show={isDisconnecting}>
		<Callout type="warning">You cannot connect this blog to the same website ID again.</Callout>

		<p>
			Are you sure you want to disconnect this blog from Hyvor Talk? This will not delete your Hyvor
			Talk Website ID. You will have to delete it manually from the Hyvor Talk Console.
		</p>

		<svelte:fragment slot="footer">
			<ButtonGroup>
				<Button variant="invisible" on:click={() => (isDisconnecting = false)}>Cancel</Button>
				<Button color="red" on:click={handleDisconnect}>Disconnect</Button>
			</ButtonGroup>
		</svelte:fragment>
	</Modal>
{/if}

<style>
	.connection-status {
		margin-bottom: 10px;
	}

	.embed-code :global(.split-control .right) {
		min-width: 0;
	}

	.embed-code {
		margin-bottom: 20px;
	}
</style>
