// frontend/src/routes/console/(nav)/[subdomain]/theme/Editor/NewFileCreator.svelte
<script lang="ts">
	import { Button, toast } from "@hyvor/design/components";
	import type { ThemeFolder } from "../../../../lib/types";
	import IconCloudUpload from '@hyvor/icons/IconCloudUpload';
import IconPlus from '@hyvor/icons/IconPlus';

	import CreateEditModal from "./Modals/CreateEditModal.svelte";
	import { getConfig } from "../../../../lib/config";
	import byteFormatter from "../../../../lib/helper/byte-formatter";
	import { createFile } from "../themeActions";
	import { addThemeFileToStore, selectedThemeFileIdStore } from "../themeStore";

    interface Props {
        folder: ThemeFolder;
    }

    let { folder }: Props = $props();

    let uploadInput: HTMLInputElement = $state();
    
    let isCreating = $state(false);

    function handleUpload() {
        const files = uploadInput.files;
        const file = files?.[0] || null;
        if (!file) {
            return toast.error('Please select a file to upload');
        }

        const maxSize = getConfig().limits.max_asset_file_size;
        if (file.size > maxSize) {
            return toast.error('File too large. Max size is ' + byteFormatter(maxSize));
        }

        const toastId = toast.loading('Uploading file...');

        createFile(
            folder, 
            file.name, 
            file
        ).then(res => {
            toast.success('File uploaded', {id: toastId});
            addThemeFileToStore(res);
            selectedThemeFileIdStore.set(res.id);
        }).catch(err => {
            toast.error(err.message || 'Unable to upload file', {id: toastId});
        });

    }

    function handleUploadClick() {
        uploadInput.click();
    }

</script>


<div class="file-creator">

    <input
        type="file"
        bind:this={uploadInput}
        style="display: none;"
        onchange={handleUpload}
    />

    <Button 
        size="x-small" 
        variant="invisible"
        on:click={() => isCreating = true}
    >
        {#snippet start()}
                <IconPlus size={11}  />
            {/snippet}
        New
    </Button>

    {#if folder === 'assets'}
        <Button 
            size="x-small" 
            variant="invisible"
            on:click={handleUploadClick}
        >
            {#snippet start()}
                        <IconCloudUpload size={11}  />
                    {/snippet}
            Upload
        </Button>
    {/if}

</div>

{#if isCreating}
    <CreateEditModal file={{id: null, name: '', folder:folder}} bind:open={isCreating} />
{/if}

<style>
    .file-creator {
        margin-top: 3px;
        margin-bottom: 4px;
    }
</style>

// resources/js/console/Theme/NewFileCreator.tsx
import React, { Fragment, useRef, useState} from 'react';
import {ThemeFolder} from "../types";
import {Check, CloudUpload, Plus, X} from "react-bootstrap-icons";
import {useThemeActions} from "./use";
import Loader from "../ReusableComponents/Loader";
import {toast} from "react-toastify";
import {appConfig} from "../helpers";
import byteFormatter from "../../helpers/byteFormatter";
import FileNameInput from "./FileNameInput";

export default function NewFileCreator({ folder } : { folder: ThemeFolder }) {

    const [isTypingName, setIsTypingName] = useState(false);
    const [isCreating, setIsCreating] = useState(false);

    const { createFile } = useThemeActions()

    function handleCreate(name: string) {
        setIsCreating(true);
        setIsTypingName(false);

        createFile({
            name,
            folder,
            content: '',
            onCreate: () => {
                setIsCreating(false);
            }
        })
    }

    const uploadRef = useRef<null | HTMLInputElement>(null);

    function handleUploadClick() {
        uploadRef.current?.click();
    }
    async function handleUpload(e: any) {
        const files = (e.target as HTMLInputElement).files;
        if (!files?.length) {
            return toast.error('No files selected');
        }
        const file = files[0];
        const maxSize = appConfig().limits.max_asset_file_size;
        if (file.size > maxSize) {
            return toast.error('File too large. Max size is ' + byteFormatter(maxSize));
        }

        setIsCreating(true);

        createFile({
            name: file.name,
            folder,
            content: file,
            onCreate: () => {
                setIsCreating(false);
            }
        })

    }

    return <div className="file-creator">

        <input
            type="file"
            ref={uploadRef}
            style={{display: 'none'}}
            onChange={handleUpload}
        />

        {
            isCreating ?
                <Loader size={10}/> :
                <Fragment>

                    {
                        !isTypingName &&
                        <Fragment>
                            <span className="new" onClick={() => setIsTypingName(true)}><Plus/> NEW</span>
                            { folder === 'assets' && <span className="new" onClick={handleUploadClick}><CloudUpload /> UPLOAD</span> }
                        </Fragment>
                    }
                    {
                        isTypingName &&
                        <FileNameInput
                            onCreate={name => handleCreate(name)}
                            onCancel={() => setIsTypingName(false)}
                        />
                    }


                </Fragment>
        }
    </div>

}
