// frontend/src/routes/console/(nav)/[subdomain]/settings/code/+page.svelte
<script lang="ts">
	import { Callout, Link, SplitControl, Switch, Text } from '@hyvor/design/components';
	import { blogStore, updateBlogStore } from '../../../../lib/stores/blogStore';
	import BlogSettingsSave from '../BlogSettingsSave.svelte';
	import CodemirrorEditor from '../../../../lib/components/CodemirrorEditor/CodemirrorEditor.svelte';

	function handleFlashloadChange(e: any) {
		updateBlogStore({ flashload: e.target.checked });
	}
</script>

<BlogSettingsSave keys={['code_head', 'code_foot', 'flashload']} />

<div class="settings">
	<div class="intro">
		<Callout type="info">
			Head and foot code will be applied to your <strong>whole blog</strong>. See <Link
				href="https://blogs.hyvor.com/docs/custom-code"
				target="_blank">docs</Link
			> for other ways to add custom code. You can use HTML or <Link
				href="/docs/themes-templates#twig"
				target="_blank">Twig</Link
			> in the code fields. <Link href="/docs/themes-templates#variables" target="_blank"
				>These variables</Link
			> are available in Twig.
		</Callout>
	</div>

	<div class="code">
		<SplitControl label="Head Code">
			{#snippet caption()}
				<div>Added right before the &lt;/head&gt; tag. Best place for styles and meta tags.</div>
			{/snippet}

			<CodemirrorEditor
				value={$blogStore.code_head || ''}
				id="comments"
				ext="twig"
				onchange={(value) => updateBlogStore({ code_head: value })}
			/>
		</SplitControl>

		<SplitControl label="Foot Code">
			{#snippet caption()}
				<div>
					Added right before the &lt;/body&gt; tag. Best place for scripts (analytics, etc.).
				</div>
			{/snippet}

			<CodemirrorEditor
				value={$blogStore.code_foot || ''}
				id="newsletter"
				ext="twig"
				onchange={(value) => updateBlogStore({ code_foot: value })}
			/>
		</SplitControl>
	</div>

	<SplitControl label="Flashload">
		{#snippet caption()}
			<div>
				<Link href="https://github.com/hyvor/flashload" target="_blank">Flashload</Link> adds a script
				to make navigation between pages faster by preloading pages when hovering over links. You may
				want to disable this if you are using other Javascript-heavy features.
			</div>
		{/snippet}

		<Switch checked={$blogStore.flashload} on:change={handleFlashloadChange} />
	</SplitControl>
</div>

<style>
	.settings {
		flex: 1;
		overflow: auto;
		padding: 25px 30px;
	}
	.settings :global(.split-control) {
		flex-direction: column;
	}

	.settings :global(.CodeMirror) {
		min-height: 200px;
	}
	.intro {
		padding: 15px;
	}
</style>

// resources/js/console/Settings/Code.tsx
import React, { useState } from 'react';
import DualSetting from '../ReusableComponents/DualSetting';
import CodemirrorEditor, { CODEMIRROR_MODES } from '../ReusableComponents/CodemirrorEditor';
import SettingsSave from '../ReusableComponents/SettingsSave';
import {useBlogActions, useBlogValues} from "../logic-helpers/blog";
import Input from "../ReusableComponents/Input";
import Switch from "../ReusableComponents/Switch";

export default function Code() {

    const { blog } = useBlogValues();
    const { updateBlogValue } = useBlogActions();

    return <div className="settings-code">

        <div className="title">
            Custom Code
        </div>
        
        <div>

            <DualSetting 
                title="Head Code"
                description={
                    <div>
                        This HTML code will be placed right before the &lt;/head&gt; tag. You can use this to add custom CSS and meta tags for the whole blog. In addition to HTML, you can also use <a className="link" href="/docs/themes-templates#twig" target="_blank">Twig</a>, and has access to <a className="link" href="/docs/themes-templates#variables" target="_blank">route variables</a>.
                    </div>
                }
                right={
                    <CodemirrorEditor
                        extension={'twig'}
                        value={blog.code_head || ''}
                        onChange={(v: string) => updateBlogValue('code_head', v)}
                    />
                }
                column={true}
            />

            <DualSetting 
                title="Foot Code"
                description="This HTML code will be placed right before the </body> tag. If you want to add custom Javascript code (ex: analytics), this is the best place to add it. You can use Twig and route variables."
                right={
                    <CodemirrorEditor
                        extension={'twig'}
                        value={blog.code_foot || ''}
                        onChange={(v: string) => updateBlogValue('code_foot', v)}
                    />
                }
                column={true}
            />

            <DualSetting
                title="Flashload"
                description={
                    <div>
                        <a
                            href="https://github.com/hyvor/flashload"
                            target="_blank"
                            className="link"
                        >Flashload</a> makes navigation between pages faster by injecting a Javascript code. You may want to disable this if you are using other Javascript-heavy features.
                    </div>
                }
                right={
                    <Switch
                        checked={blog.flashload}
                        onChange={checked => updateBlogValue('flashload', checked)}
                    />
                }
            />

        </div>

        <SettingsSave keys={
            [
                'code_head',
                'code_foot',
                'flashload'
            ]
        } />

    </div>

}
