// frontend/src/routes/console/[subdomain]/settings/color-mode/+page.svelte
<script lang="ts">
	import { FormControl, InputGroup, Radio, SplitControl, Switch } from "@hyvor/design/components";
	import { blogStore, updateBlogStore } from "../../../lib/stores/blogStore";
	import CodemirrorEditor from "../../../lib/components/CodemirrorEditor/CodemirrorEditor.svelte";
	import BlogSettingsSave from "../BlogSettingsSave.svelte";

    function handleColorModeChange(value: 'light' | 'dark' | 'both') {
        updateBlogStore({ color_modes: value });
    }


    function handleColorModeDefaultChange(value: 'light' | 'dark' | 'os') {
        updateBlogStore({ color_mode_default: value });
    }

</script>

<BlogSettingsSave 
    keys={['color_modes', 'color_mode_default']}
/>

<div class="settings">
        
    <SplitControl
        label="Color Mode(s)"
        caption="Which color mode(s) should be available to your readers?"
    >


        <InputGroup>

            <Radio 
                value="light" 
                group={$blogStore.color_modes}
                on:change={e => handleColorModeChange('light')}
            >
                Light
            </Radio>

            <Radio
                value="dark" 
                group={$blogStore.color_modes}
                on:change={e => handleColorModeChange('dark')}
            >
                Dark
            </Radio>

            <Radio
                value="both" 
                group={$blogStore.color_modes}
                on:change={e => handleColorModeChange('both')}
            >
                Both
            </Radio>

        </InputGroup>

    </SplitControl>

    <SplitControl
        label="Default Color Mode"
        caption="Which color mode should be the default?"
    >

        <InputGroup>

            <Radio 
                value="os"
                group={$blogStore.color_mode_default}
                on:change={e => handleColorModeDefaultChange('os')}
            >
                User's Operating System (OS) Preference
            </Radio>

            <Radio 
                value="light" 
                group={$blogStore.color_mode_default}
                on:change={e => handleColorModeDefaultChange('light')}
            >
                Light
            </Radio>

            <Radio 
                value="dark" 
                group={$blogStore.color_mode_default}
                on:change={e => handleColorModeDefaultChange('dark')}
            >
                Dark
            </Radio>


        </InputGroup>

    </SplitControl>

</div>

<style>
    .settings {
        flex: 1;
        overflow: auto;
        padding: 25px 30px;
    }
</style>

// resources/js/console/Settings/ColorMode.tsx
import React from 'react';
import DualSetting from "../ReusableComponents/DualSetting";
import Radio from "../ReusableComponents/Radio";
import SettingsSave from "../ReusableComponents/SettingsSave";
import {useBlogActions, useBlogValues} from "./useBlog";

export default function ColorMode() {
    
    const { blog } = useBlogValues();
    const { updateBlogValue } = useBlogActions();
    
    function handleColorModeChange(value: string) {
        updateBlogValue("color_modes", value);
    }
    function handleColorModeDefaultChange(value: string) {
        updateBlogValue("color_mode_default", value);
    }
    
    return <div className="settings-color-mode">

        <div className="title">
            Light & Dark Modes
        </div>

        <DualSetting
            title="Color Mode(s)"
            description="What color modes do you want in your blog?"
            right={
                <div>
                    <Radio
                        name="color-modes"
                        placeholder="Both"
                        value="both"
                        onChange={handleColorModeChange}
                        checkFor={blog.color_modes}
                    />
                    <Radio
                        name="color-modes"
                        placeholder="Light"
                        value="light"
                        onChange={handleColorModeChange}
                        checkFor={blog.color_modes}
                    />
                    <Radio
                        name="color-modes"
                        placeholder="Dark"
                        value="dark"
                        onChange={handleColorModeChange}
                        checkFor={blog.color_modes}
                    />
                </div>
            }
        />

        {
            blog.color_modes === 'both' ?

                <DualSetting
                    title="Default Color Mode"
                    description="Which color mode should users see by default?"
                    right={
                        <div>
                            <Radio
                                name="color-mode-default"
                                placeholder="User's Operating System (OS) Preference"
                                value="os"
                                onChange={handleColorModeDefaultChange}
                                checkFor={blog.color_mode_default}
                            />
                            <Radio
                                name="color-mode-default"
                                placeholder="Light"
                                value="light"
                                onChange={handleColorModeDefaultChange}
                                checkFor={blog.color_mode_default}
                            />
                            <Radio
                                name="color-mode-default"
                                placeholder="Dark"
                                value="dark"
                                onChange={handleColorModeDefaultChange}
                                checkFor={blog.color_mode_default}
                            />
                        </div>
                    }
                /> : null
        }
        
        <SettingsSave keys={
            [
                'color_modes', 'color_mode_default'
            ]
        } />
        
    </div>
    
}
