// frontend/src/routes/console/lib/components/CodemirrorEditor/CodemirrorEditor.svelte
<script lang="ts">
	import { createEventDispatcher, onMount } from "svelte";
    import './codemirror';
	import { CODEMIRROR_MODES, importCodemirrorAll } from "./codemirror";

    export let value: string;
    export let ext: keyof typeof CODEMIRROR_MODES;
    export let id: string | number;

    $: tabSize = ext === 'yaml' ? 2 : 4;

    let editorDiv: HTMLDivElement;
    let cm: any;

    const dispatch = createEventDispatcher();

    async function initCm() {

        await importCodemirrorAll();

        editorDiv.innerHTML = "";

        function handleSave() {
            dispatch('save', cm.current.doc.getValue());
        }

        function handleTab(cm: any) {
            if (cm.somethingSelected()) {
                cm.indentSelection("add");
            } else {
                cm.replaceSelection(cm.getOption("indentWithTabs")? "\t":
                    Array(cm.getOption("indentUnit") + 1).join(" "), "end", "+input");
            }
        }

        cm = (window as any).CodeMirror(editorDiv, {
            value,
            mode: CODEMIRROR_MODES[ext],
            theme: 'solarized',
            keyMap: 'sublime',
            tabSize,
            indentWithTabs: false,
            indentUnit: tabSize,
            lineWrapping: false,
            lineNumbers: true,
            matchBrackets: true,
            matchTags: {bothTags: true},
            autoCloseBrackets: true,
            autoCloseTags: true,
            extraKeys: {
                "Ctrl-S": handleSave,
                "Cmd-S": handleSave,
                "Tab": handleTab
            }
        })
        cm.on('change', function() {
            const val = cm.doc.getValue();
            dispatch('change', val);
        })

    }

    onMount(initCm);

    // re-create codemirror instance when id changes
    $: if (id) {
        initCm();
    }

</script>



<div 
    class="editor"
    bind:this={editorDiv}
></div>

<style lang="scss">


    .editor {
        height: 100%;
    }

    .editor :global(.CodeMirror) {
        height:100%;
        font-family: 'source-code-pro', Menlo, 'Courier New', Consolas, monospace!important;
        box-shadow: none!important;
        border-radius:20px;
        background-color: var(--input)!important;
        font-size: 14px;
        line-height: 21px;
        :global(.CodeMirror-line) {
            padding-left: 15px!important;
        }
        :global(.CodeMirror-gutters) {
            background-color: var(--input);
        }
        :global(.CodeMirror-scroll) {
            overflow-x: hidden!important;
        }
    }

</style>

// resources/js/console/ReusableComponents/CodemirrorEditor.tsx
import React, {useEffect, useRef} from 'react'

export const CODEMIRROR_MODES = {
    scss: { name: 'twig', base: 'text/x-scss'},
    twig: { name: 'twig', base: 'text/html' },
    js: 'text/javascript',
    yaml: 'text/x-yaml'
}

interface Props {

    /**
     * Send an ID if the same component is used for multiple different values/files
     * (for example in theme file editing)
     */
    id?: null | string | number,
    value: string,
    onChange: (val: string) => any,
    onSave?: (val: string) => any,
    extension: keyof typeof CODEMIRROR_MODES,
}

export default function CodemirrorEditor({ id = null, value, onChange, onSave, extension } : Props) {

    const ref = useRef<null | HTMLDivElement>(null);
    const cm = useRef<any>(null);
    const tabSize = extension === 'yaml' ? 2 : 4;

    function handleTab(cm: any) {
        console.log(cm)
        if (cm.somethingSelected()) {
          cm.indentSelection("add");
        } else {
          cm.replaceSelection(cm.getOption("indentWithTabs")? "\t":
            Array(cm.getOption("indentUnit") + 1).join(" "), "end", "+input");
        }
    }

    function initCm() {

        (ref.current as HTMLDivElement).innerHTML = "";

        function handleSave() {
            onSave && onSave(cm.current.doc.getValue())
        }

        cm.current = (window as any).CodeMirror(ref.current, {
            value,
            mode: CODEMIRROR_MODES[extension],
            theme: 'solarized',
            keyMap: 'sublime',
            tabSize,
            indentWithTabs: false,
            indentUnit: tabSize,
            lineWrapping: false,
            lineNumbers: true,
            matchBrackets: true,
            matchTags: {bothTags: true},
            autoCloseBrackets: true,
            autoCloseTags: true,
            extraKeys: {
                "Ctrl-S": handleSave,
                "Cmd-S": handleSave,
                "Tab": handleTab
            }
        })
        cm.current.on('change', function() {
            const val = cm.current.doc.getValue()
            onChange(val)
        })

    }

    useEffect(() => {
        if (cm.current)
            return;
        initCm()
    }, []);

    useEffect(() => {
        initCm()
    }, [id])

    return <div className="global-codemirror-wrap" ref={ref} />

}
