// resources/js/console/ReusableComponents/UpgradeRequired.tsx
import { Fragment, ReactNode } from "react";
import { SubscriptionPlan } from "../types";
import { getSubscription, isInTrial } from "../lib/blog-helpers";
import getSubdomain from "../logic-helpers/subdomain";
import React from "react";
import { ArrowUpCircle } from "react-bootstrap-icons";
import Button from "./Button";

const allPlanTypes : SubscriptionPlan[] = [
    'starter',
    'growth',
    'premium',
    'team',
    'business',
    'enterprise'
];

export default function UpgradeRequired(
    {minPlan, trialAllowed, children, text, allow} :
    {
        // minimum plan requirement
        minPlan: SubscriptionPlan,
        // whether allowed in the trial period 
        trialAllowed: boolean, 
        // allow to bypass the upgrade required
        allow?: boolean,
        children: ReactNode, 
        text: ReactNode
    }
) {

    const subdomain = getSubdomain();

    const blogSubscription = getSubscription(subdomain);
    const blogInTrial = isInTrial(subdomain);

    const hasMinPlan = blogSubscription && 
        allPlanTypes.indexOf(blogSubscription.plan) >= allPlanTypes.indexOf(minPlan);

    if (hasMinPlan || (trialAllowed && blogInTrial) || allow) {
        return <Fragment>{children}</Fragment>;
    }

    return <div className="global-upgrade-required">

        <div className="upgrade-inner">

            <div className="upgrade-required-title">
                <ArrowUpCircle/> 
                <span>Upgrade Required</span>
            </div>

            <div className="upgrade-required-content">

                { text }

            </div>

            <div className="upgrade-cta">

                <a
                    className="button primary small blue" 
                    href={`/console/` + subdomain + `/billing`}
                    target="_blank"
                >Upgrade Now</a>

            </div>

        </div>


    </div>
    

}

// frontend/src/routes/console/[subdomain]/billing/UpgradeRequired.svelte
<script lang="ts">
	import { IconArrowUpCircle } from "@hyvor/icons";
	import { isInTrial, subscriptionStore } from "../../lib/stores/subscriptionStore";
	import type { SubscriptionPlan } from "../../lib/types";
	import { Button } from "@hyvor/design/components";
	import { blogStore } from "../../lib/stores/blogStore";

    const allPlanTypes : SubscriptionPlan[] = [
        'starter',
        'growth',
        'premium',
        'team',
        'business',
        'enterprise'
    ];

    export let minPlan : SubscriptionPlan;
    export let trialAllowed = false;
    export let allow = false;

    const inTrial = isInTrial();

    $: hasMinPlan = $subscriptionStore && 
        allPlanTypes.indexOf($subscriptionStore.plan) >= allPlanTypes.indexOf(minPlan);

</script>


{#if hasMinPlan || (trialAllowed && inTrial) || allow}
    <slot />
{:else}

    <div class="upgrade-required">

        <div class="upgrade-inner">

            <div class="upgrade-required-title">
                <IconArrowUpCircle />
                <span>Upgrade Required</span>
            </div>

            <div class="upgrade-required-content">
                <slot name="upgrade-text" />
            </div>

            <div class="upgrade-cta">
                <Button as="a" href={`/console/` + $blogStore.subdomain + `/billing`}>
                    Upgrade Now
                </Button>
            </div>

        </div>
    </div>

{/if}


<style>

    .upgrade-required {
        padding: 20px;
        width: 100%;
        height: 100%;
        flex: 1;
    }
    .upgrade-inner {
        padding: 20px 25px;
        background-color: var(--blue-light);
        border-radius: 20px;
        width: 550px;
        max-width: 100%;
        margin: auto;
    }
    .upgrade-required-title {
        font-size: 1.2rem;
        font-weight: 600;
        text-align: center;
        display: flex;
        align-items: center;
        justify-content: center;
    }
    .upgrade-required-title :global(svg) {
        margin-right: 8px;
    }
    .upgrade-required-content {
        margin-top: 20px;
        text-align: center;
        line-height: 20px;
    }
    .upgrade-cta {
        margin-top: 20px;
        text-align: center;
    }

</style>
