// resources/js/console/Posts/Post/New/Publish/UnpublishButton.tsx
import React, { Fragment, useState } from "react";
import { usePostActions, usePostValues } from "../../helpers";
import { PopupConfirm } from "../../../../ReusableComponents/Popup";
import { toast } from "react-toastify";
import { bringLeftHeaderToFront } from "../z-index";


export default function UnpublishButton({id} : {id: number}) {

    const { currentVariant } = usePostValues(id);
    const { saveCurrentVariantDiff } = usePostActions(id);
    const [isUnpublishing, setIsUnpublishing] = useState(false);

    const status = currentVariant.status;

    if (status !== 'published' && status !== 'scheduled') {
        return null;
    }

    function handleUnpublish() {
        saveCurrentVariantDiff({
            diff: {
                status: 'draft',
            },
            onSave: () => {
                toast("Post unpublished");
            }
        });

        setIsUnpublishing(false);
    }

    return <Fragment>
        <button
            className="button medium light unpublish-button"
            onClick={() => {
                bringLeftHeaderToFront();
                setIsUnpublishing(true)
            }}
        >
            { status === 'published' ? "Unpublish" : "Unschedule" }
        </button>
        
        {
            isUnpublishing && <PopupConfirm
                title={( status === 'published' ? 'Unpublish' : 'Unschedule' ) + " Post"}
                text={"Are you sure to " + ( status === 'published' ? 'unpublish' : 'unschedule' ) + " this post? It will be changed to a draft."}
                name={( status === 'published' ? 'Unpublish' : 'Unschedule' )}
                onClick={handleUnpublish}
                onCancel={() => setIsUnpublishing(false)}
            />
        }

    </Fragment>

}

// frontend/src/routes/console/[subdomain]/posts/[postId]/Header/Buttons/UnpublishButton.svelte
<script lang="ts">
	import { Button, Modal, toast } from "@hyvor/design/components";
	import { postVariantStore } from "../../../postStore";
	import { updatePostVariant } from "../../../postActions";

    let modalOpen = false;

    function handleUnpublish() {

        modalOpen = false;

        const toastId = toast.loading('Unpublishing...');

        updatePostVariant({
            status: 'draft'
        }).then(() => {
            toast.success('Post unpublished', {id: toastId})
        }).catch(() => {
            toast.error('Failed to unpublish post', {id: toastId})
        });

    }

</script>

{#if $postVariantStore.status !== 'draft'}
    <Button
        size="medium" 
        color="light"
        slot="trigger"
        on:click={() => modalOpen = true}
    >
        {#if $postVariantStore.status === 'scheduled'}
            Unschedule
        {:else}
            Unpublish
        {/if}
    </Button>

    <Modal 
        title={$postVariantStore.status === 'scheduled' ? 'Unschedule Post' : 'Unpublish Post'} 
        bind:show={modalOpen}
        size="small"
    >

        Are you sure to {$postVariantStore.status === 'published' ? 'unpublish' : 'unschedule'} this post? It's status will be changed to draft.

        <div slot="footer">
            <Button color="invisible" on:click={() => modalOpen = false}>Cancel</Button>
            <Button color="danger" on:click={handleUnpublish}>
                {$postVariantStore.status === 'scheduled' ? 'Unschedule' : 'Unpublish'}
            </Button>
        </div>

    </Modal>

{/if}
