// backend/resources/js/console/Theme/Download.tsx
import React, {Fragment, useState} from "react";
import {PopupConfirm} from "../ReusableComponents/Popup";
import {getEndpoint} from "../lib/api";
import getSubdomain from "../logic-helpers/subdomain";
import {CloudDownload} from "react-bootstrap-icons";

export default function Download() {

    const [ isDownloading, setIsDownloading ] = useState(false);

    function handleDownload() {
        window.open(getEndpoint(getSubdomain(), '/theme/download'));
        setIsDownloading(false)
    }

    return <Fragment>
        <button onClick={() => setIsDownloading(true)} className="button inactive small">Download <CloudDownload /></button>
        {
            isDownloading ?
                <PopupConfirm
                    title="Download Theme"
                    text="Download your theme as a ZIP file."
                    name="Download"
                    onClick={handleDownload}
                    onCancel={() => setIsDownloading(false)}
                />
            : null
        }
    </Fragment>

}

// frontend/src/routes/console/[subdomain]/theme/Download.svelte
<script>
	import { Button, Tooltip, confirm } from '@hyvor/design/components';
	import { IconCloudDownload } from '@hyvor/icons';
	import { blogStore } from '../../lib/stores/blogStore';

	async function handleDownload() {
		if (
			await confirm({
				title: 'Download theme',
				content:
					'Your theme files will be downloaded as a zip file. You can upload it to another blog.',
				confirmText: 'Yes, download'
			})
		) {
			const url = '/api/console/v0/blog/' + $blogStore.subdomain + '/theme/download';

			window.open(url, '_blank');
		}
	}
</script>

<Tooltip text="Download your theme files">
	<Button color="input" size="small" style="font-size:13px" on:click={handleDownload}>
		<IconCloudDownload size={16} slot="start" />
		Download
	</Button>
</Tooltip>
