// backend/resources/js/console/Theme/Upload.tsx
import React, {Fragment, useRef, useState} from "react";
import {CloudUpload} from "react-bootstrap-icons";
import {toast} from "react-toastify";
import {appConfig} from "../helpers";
import {useActions} from "kea";
import themeLogic from "../logic/themeLogic";
import getSubdomain from "../logic-helpers/subdomain";
import Spinner from "../ReusableComponents/Spinner";


export default function Upload() {

    const { uploadTheme } = useActions(themeLogic({subdomain: getSubdomain()}));

    const inputRef = useRef<HTMLInputElement | null>(null)
    const [ isUploading, setIsUploading ] = useState(false)

    function handleClick() {
        (inputRef.current as HTMLInputElement).click()
    }

    function handleUpload() {
        const files = (inputRef.current as HTMLInputElement).files;
        if (!files || files.length !== 1) {
            return toast.error("Please select a file");
        }
        const file = files[0];

        const max = appConfig().limits.max_theme_zip_size_kb;
        if (file.size > max * 1000) {
            return toast.error("Max file size is" + (max / 1000) + "MB");
        }

        setIsUploading(true)
        uploadTheme({
            zip: file,
            onUpload: () => {
                setIsUploading(false)
                toast.success("Theme uploading completed");
            }
        });
    }

    return <Fragment>
        <button
            onClick={handleClick}
            className="button inactive small"
        >{ isUploading ? "Uploading" : "Upload" }&nbsp;{ isUploading ? <Spinner size={7} dark={true} /> : <CloudUpload /> }</button>
        {/* https://stackoverflow.com/a/56357139/9059939 */}
        <input
            ref={inputRef}
            type="file"
            hidden={true}
            accept="zip,application/octet-stream,application/zip,application/x-zip,application/x-zip-compressed"
            onChange={handleUpload}
        />
    </Fragment>

}

// frontend/src/routes/console/[subdomain]/theme/Upload.svelte
<script lang="ts">
	import { Button, Tooltip, toast } from "@hyvor/design/components";
	import { IconCloudUpload } from "@hyvor/icons";
	import { getConfig } from "../../lib/config";
	import byteFormatter from "../../lib/helper/byte-formatter";
	import { uploadTheme } from "./themeActions";
	import { setThemeFiles } from "./themeStore";

    let inputEl : HTMLInputElement;

    function handleClick() {
        inputEl.click()
    }

    function handleUpload() {

        const file = inputEl.files?.[0];

        if (!file) {
            return toast.error("Please select a file");
        }

        const max = getConfig().limits.max_theme_zip_size;
        if (file.size > max) {
            return toast.error("Max file size is" + byteFormatter(max));
        }

        const toastId = toast.loading("Uploading theme...");

        uploadTheme(file)
            .then(files => {
                toast.success("Theme uploading completed", {id: toastId});
                setThemeFiles(files);
            })
            .catch(err => {
                toast.error(err.message, {id: toastId});
            });

    }
</script>

<Tooltip
    text="Upload a theme from a zip file"
>

    <Button 
        color="input" 
        size="small" 
        style="font-size:13px"
        on:click={handleClick}
    >
        <IconCloudUpload size={16} slot="start" />
        Upload
    </Button>

    <input
        bind:this={inputEl}
        type="file"
        accept="zip,application/octet-stream,application/zip,application/x-zip,application/x-zip-compressed"
        on:change={handleUpload}
        style="display:none"
    />

</Tooltip>
