// frontend/src/routes/console/[subdomain]/theme/Editor/Preview/TextEditor.svelte
<script lang="ts">
	import CodemirrorEditor from "../../../../lib/components/CodemirrorEditor/CodemirrorEditor.svelte";
	import type { CodeMirrorMode } from "../../../../lib/components/CodemirrorEditor/codemirror";
	import { updateThemeFileStore } from "../../themeStore";
	import type { ThemeFile } from "../../../../lib/types";
	import { saveCurrentFile } from "../../theme";

    export let file: ThemeFile;
    export let ext: CodeMirrorMode;

    function handleChange(val: string) {
        updateThemeFileStore(file.id, {content: val});
    }

    function handleTextSave(e: CustomEvent<string>) {
        saveCurrentFile();
    }

    function handleKeydown(e: KeyboardEvent) {
        if ((e.ctrlKey || e.metaKey) && e.key === 's') {
            e.preventDefault();
        }
    }

</script>

<svelte:window on:keydown={handleKeydown} />

<div class="text-editor">
    <CodemirrorEditor 
        value={file.content || ''}
        id={file.id}
        ext={ext}
        on:change={e => handleChange(e.detail)}
        on:save={handleTextSave}
    />
</div>

<style>
    .text-editor {
        flex: 1;
        min-height: 0;
        height: 100%;
    }
    .text-editor :global(.CodeMirror) {
        padding: 10px 0 60px;
        border-radius: 0;
        height: 100%;
    }
</style>

// resources/js/console/Theme/FilePreview/TextEditor.tsx
import CodemirrorEditor, {CODEMIRROR_MODES} from "../../ReusableComponents/CodemirrorEditor";
import React, {useEffect} from "react";
import {ThemeFile} from "../../types";
import {useThemeActions} from "../use";


export default function TextEditor({ file, ext } : {file: ThemeFile, ext: keyof typeof CODEMIRROR_MODES}) {

    const { setFileContent, editorSaveFile } = useThemeActions()

    function handleKeyPress(e: KeyboardEvent) {
        if (e.key === "s" && (e.ctrlKey || e.metaKey)) {
            editorSaveFile(file.id);
        }
    }

    useEffect(() => {
        document.addEventListener("keydown", handleKeyPress);
        return () => document.removeEventListener("keydown", handleKeyPress);
    }, []);

    return <div className="text-editor">

        <CodemirrorEditor
            value={file.content || ''}
            onChange={(val: string) => setFileContent(file.id, val)}
            mode={ext}
        />

    </div>

}
